# Generated by Django 2.0.2 on 2019-06-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data', '0003_auto_20190428_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='ca_meter',
            new_name='p1ca_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='cb_meter',
            new_name='p1cb_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='cin_house',
            new_name='p1va_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='energy',
            new_name='p1vb_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='latitude',
            new_name='p2ca_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='longitude',
            new_name='p2cb_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='va_meter',
            new_name='p2va_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='vb_meter',
            new_name='p2vb_meter',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='vin_house',
            new_name='p3ca_meter',
        ),
        migrations.RemoveField(
            model_name='data',
            name='location',
        ),
        migrations.AddField(
            model_name='data',
            name='p3cb_meter',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='p3va_meter',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='p3vb_meter',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
